name: Krzysztof Begiedza
encoding: utf-8

permalink: /:title

# Markdown stuff
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
    math_engine: mathjax

collections_dir: tutorials
collections:
    zero:
        output: true
        permalink: /:name
    one:
        output: true
        permalink: /:name