author: Krzysztof Begiedza
title: Blog - Krzysztof Begiedza
description: Blog - Krzysztof Begiedza
encoding: utf-8

permalink: /:title

sass:
    style: compressed

# Markdown stuff
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
    math_engine: mathjax

collections_dir: tutorials
collections:
    one:
        output: true
        permalink: /:collection/:title

plugins:
    - jekyll-feed
    - jekyll-sitemap
